services:
  - type: web
    name: flask-admin-advanced
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      # Set this manually or attach a managed Postgres and use its internal URL
      # - key: DATABASE_URL
      #   value: postgresql+psycopg2://...